{{- if .Values.ingress.enabled -}}
apiVersion: v1
data:
  tls.crt: {{ .Values.secret.crt }}
  tls.key: {{ .Values.secret.key }}
kind: Secret
metadata:
  name: httpserver-tls
type: kubernetes.io/tls
{{- end }}